### ISSUE TITLE
when i adding extension 

### ISSUE THREAD

**Issue by ItsBluey** [Revadike/SteamWebIntegration#64] opened 2023-02-28 09:31 UTC
![image](https://user-images.githubusercontent.com/20117258/221811460-71a0e6a3-c7b0-4acc-ad77-61a55e50f0e9.png)

**Comment by Revadike** [comment] 2023-02-28 10:23
Dupe of https://github.com/Revadike/SteamWebIntegration/issues/63

**Closed by Revadike** 2023-02-28 10:23 UTC
