### ISSUE TITLE
[BUG] Page has been updated but the link has not been rechecked

### ISSUE THREAD

**Issue by bestpika** [Revadike/SteamWebIntegration#51] opened 2021-03-19 06:09 UTC
On Fanatical's bundle page, click on the product and then click left or right to change the product does not recheck the link.
The link will not be rechecked unless I use the "Clear and run (reload)" command directly.
e.g. <https://www.fanatical.com/en/bundle/nitro-bundle>

**Comment by Revadike** [comment] 2021-03-19 09:22
Dupe of https://github.com/Revadike/SteamWebIntegration/issues/16

**Closed by Revadike** 2021-03-19 09:22 UTC
